name: Run Tkinter GUI Chatbot

on: [push, pull_request]  # 触发条件

jobs:
  build:
    runs-on: ubuntu-latest  # 使用 Ubuntu 作为运行环境

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4  # 拉取代码

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'  # 选择 Python 版本

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install requests  # 安装 requests 库

      - name: Install Xvfb and required GUI libraries
        run: |
          sudo apt-get update
          sudo apt-get install -y xvfb python3-tk x11-apps  # 安装 Tkinter 依赖

      - name: Run Tkinter GUI using Xvfb
        run: |
          Xvfb :99 -screen 0 1920x1080x24 &  # 启动虚拟显示服务器
          export DISPLAY=:99  # 设置显示变量
          python chatbot.py &  # 运行 Tkinter GUI
          sleep 10  # 让 GUI 运行 10 秒
          pkill -f chatbot.py  # 关闭 Tkinter 进程
